services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: agro_postgres
    environment:
      POSTGRES_DB: agro_geo
      POSTGRES_USER: agro
      POSTGRES_PASSWORD: agro
    ports:
      - "5432:5432"
    volumes:
      - agro_pg:/var/lib/postgresql/data

  api:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: agro_geo_api
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: agro_geo
      POSTGRES_USER: agro
      POSTGRES_PASSWORD: agro
    ports:
      - "8000:8000"
    depends_on:
      - postgres
  osrm-prep:
    image: osrm/osrm-backend:latest
    container_name: agro_osrm_prep
    working_dir: /data
    volumes:
      - ./osrm_data:/data
      - ./osrm:/scripts:ro
    command: ["sh", "-lc", "cp /scripts/prepare.sh /tmp/prepare.sh && sed -i 's/\r$//' /tmp/prepare.sh && sh /tmp/prepare.sh"]
    restart: "no"

  osrm:
    image: osrm/osrm-backend:latest
    container_name: agro_osrm
    working_dir: /data
    volumes:
      - ./osrm_data:/data
    ports:
      - "5000:5000"
    command: ["osrm-routed", "--algorithm", "ch", "/data/map.osrm"]
    depends_on:
      osrm-prep:
        condition: service_completed_successfully

volumes:
  agro_pg:
